<a href="https://colab.research.google.com/github/abhijeetmahamuni1/EV-Market-Analysis/blob/main/EV_(Electric_Vehicle)_Market_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# EV (Electric Vehicle) Market Analysis

1 How are EV registrations changing over time?
2 Which EV manufacturer has the highest market share?
3 Which EV model is most popular?
4 Which state has the highest EV adoption?
5 Which vehicle category is growing fastest?
6 What is the average EV price by manufacturer?
7 How does battery range vary by manufacturer?
8 Is vehicle price related to battery range?
9 Which states show the strongest EV growth?
10 What factors appear to influence EV adoption?

And importantly: I won't give you a clean dataset. You'll have to inspect → clean → transform → analyze → visualize → explain, just like a real analyst.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_csv("/content/drive/MyDrive/practice_data_set/EV_Market_Analysis_Unclean_Dataset.csv")

In [9]:
df.head()

,Record_ID,Registration_Date,Manufacturer,Model,Vehicle_Category,City,State,Price_INR,Battery_Range_KM,Units_Sold,Charging_Type,Area_Type
0,EV100000,2024-10-08,Tata,Punch EV,Electric Scooter,Delhi,Tamil Nadu,200075,91.0,15.0,Home,Rural
1,EV100001,2025-08-27,Tesla,Model 3,Electric Scooter,Ahmedabad,Maharashtra,97011,74.0,21.0,Home,Urban
2,EV100002,2024-07-22,Tata,Punch EV,Electric Scooter,Kolkata,Uttar Pradesh,250000,133.0,28.0,Fast Charging,Rural
3,EV100003,2025-12-15,Tata,Nexon EV,Electric Car,Ahmedabad,Telangana,2386927,297.0,11.0,Home,Semi-Urban
4,EV100004,2025-01-02,tata,S1 Pro,Electric Car,Chennai,West Bengal,3456598,291.0,3.0,Home,Rural

In [10]:
df.shape

(1225, 12)

In [11]:
df.columns

Index(['Record_ID', 'Registration_Date', 'Manufacturer', 'Model',
       'Vehicle_Category', 'City', 'State', 'Price_INR', 'Battery_Range_KM',
       'Units_Sold', 'Charging_Type', 'Area_Type'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1225 entries, 0 to 1224
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Record_ID          1225 non-null   object
 1   Registration_Date  1225 non-null   object
 2   Manufacturer       1225 non-null   object
 3   Model              1225 non-null   object
 4   Vehicle_Category   1225 non-null   object
 5   City               1225 non-null   object
 6   State              1207 non-null   object
 7   Price_INR          1207 non-null   object
 8   Battery_Range_KM   1197 non-null   float64
 9   Units_Sold         1220 non-null   float64
 10  Charging_Type      1225 non-null   object
 11  Area_Type          1225 non-null   object
dtypes: float64(2), object(10)
memory usage: 115.0+ KB

In [13]:
df.describe()

       Battery_Range_KM   Units_Sold
count       1197.000000  1220.000000
mean         254.077694    25.085246
std          147.911966    75.076057
min           70.000000    -5.000000
25%          141.000000    10.000000
50%          203.000000    17.000000
75%          361.000000    26.000000
max          599.000000   999.000000

In [14]:
df.isnull().sum()

Record_ID             0
Registration_Date     0
Manufacturer          0
Model                 0
Vehicle_Category      0
City                  0
State                18
Price_INR            18
Battery_Range_KM     28
Units_Sold            5
Charging_Type         0
Area_Type             0
dtype: int64

In [15]:
df.dtypes

Record_ID             object
Registration_Date     object
Manufacturer          object
Model                 object
Vehicle_Category      object
City                  object
State                 object
Price_INR             object
Battery_Range_KM     float64
Units_Sold           float64
Charging_Type         object
Area_Type             object
dtype: object

In [16]:
df.duplicated().sum()

np.int64(25)

In [17]:
df.nunique()

Record_ID            1200
Registration_Date     707
Manufacturer           13
Model                  22
Vehicle_Category        3
City                   17
State                  10
Price_INR            1023
Battery_Range_KM      422
Units_Sold             71
Charging_Type           3
Area_Type               3
dtype: int64

In [18]:
df[df.duplicated()]

,Record_ID,Registration_Date,Manufacturer,Model,Vehicle_Category,City,State,Price_INR,Battery_Range_KM,Units_Sold,Charging_Type,Area_Type
1200,EV100459,2026-01-24,Ola,S1 X,Electric Bike,Mumbai,West Bengal,116794,200.0,35.0,Public,Urban
1201,EV100457,2025-11-02,BYD,Seal,Electric Car,Kolkata,Gujarat,3215480,259.0,10.0,Public,Urban
1202,EV101022,2026-02-19,Tesla,Model Y,Electric Car,Ahmedabad,Uttar Pradesh,3303451,214.0,2.0,Public,Rural
1203,EV100141,2024-03-03,Kia,Carens EV,Electric Car,Ahmedabad,Gujarat,4008866,260.0,31.0,Home,Semi-Urban
1204,EV100668,2026-08-29,Tata,Nexon EV,Electric Car,Jaipur,Karnataka,2317756,545.0,47.0,Fast Charging,Urban
1205,EV101011,2026-08-30,Tesla,Model Y,Electric Car,Pune,Gujarat,2119537,205.0,11.0,Fast Charging,Rural
1206,EV100151,2025-04-09,Tesla,Model Y,Electric Bike,Kochi,West Bengal,350000,153.0,42.0,Public,Urban
1207,EV100830,2024-06-19,BYD,Seal,Electric Car,Jaipur,Karnataka,3092203,479.0,26.0,Fast Charging,Urban
1208,EV100750,2025-04-10,Ola,S1 Pro,Electric Bike,Kochi,Kerala,109337,174.0,28.0,Fast Charging,Semi-Urban
1209,EV100046,2024-11-08,Ather,Rizta,Electric Car,Delhi,Tamil Nadu,4036943,190.0,58.0,Home,Semi-Urban
1210,EV101132,2024-03-12,Tata,Nexon EV,Electric Scooter,Kolkata,Kerala,80190,149.0,3.0,Public,Semi-Urban
1211,EV100128,2025-09-13,BYD,Atto 3,Electric Scooter,Chennai,Tamil Nadu,184026,165.0,41.0,Public,Semi-Urban
1212,EV100034,2024-07-28,Kia,Carens EV,Electric Scooter,Lucknow,Telangana,116658,106.0,13.0,Fast Charging,Urban
1213,EV100280,2025-05-30,Tata,Nexon EV,Electric Car,Bengaluru,Tamil Nadu,2997885,523.0,25.0,Public,Rural
1214,EV100594,2026-08-20,Ola,S1 X,Electric Car,Kochi,Maharashtra,2990867,391.0,23.0,Fast Charging,Rural
1215,EV100721,2026-07-24,Tata,Nexon EV,Electric Car,Pune,Rajasthan,3217268,393.0,4.0,Fast Charging,Rural
1216,EV101128,2025-02-11,MG,Comet EV,Electric Car,Kolkata,West Bengal,1886551,589.0,13.0,Home,Rural
1217,EV100399,2024-01-13,Hyundai,Kona Electric,Electric Scooter,Mumbai,Tamil Nadu,196137,90.0,31.0,Fast Charging,Semi-Urban
1218,EV100694,2025-02-06,Tesla,Model 3,Electric Car,Ahmedabad,Telangana,1782656,369.0,23.0,Home,Semi-Urban
1219,EV100109,2025-02-21,Tata,Punch EV,Electric Car,Pune,Tamil Nadu,5500000,597.0,28.0,Home,Semi-Urban
1220,EV100669,2025-04-05,MG,Comet EV,Electric Car,Hyderabad,Maharashtra,2027227,319.0,7.0,Public,Rural
1221,EV100887,2024-06-22,MG,Comet EV,Electric Bike,Mumbai,Uttar Pradesh,176278,135.0,28.0,Fast Charging,Rural
1222,EV100474,2024-01-20,Hyundai,Ioniq 5,Electric Scooter,Delhi,Tamil Nadu,88663,179.0,13.0,Home,Urban
1223,EV101163,2024-05-20,Hyundai,Creta Electric,Electric Car,Hyderabad,Rajasthan,2204204,302.0,35.0,Home,Urban
1224,EV100544,2025-03-14,Kia,Carens EV,Electric Car,Nagpur,Maharashtra,2528053,312.0,31.0,Home,Rural

In [19]:
df = df.drop_duplicates()

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.shape

(1200, 12)

In [22]:
df["Manufacturer"].value_counts()

Manufacturer
Hyundai        154
Ola            139
Mahindra       132
Tesla          130
Tata           130
Ather          124
MG             122
BYD            120
Kia            114
tata            10
Tata Motors     10
MG               9
TATA             6
Name: count, dtype: int64

In [23]:
df["Manufacturer"] = df["Manufacturer"].str.strip()  # strip() remove extra spaces

In [24]:
df["Manufacturer"].value_counts()

Manufacturer
Hyundai        154
Ola            139
Mahindra       132
MG             131
Tata           130
Tesla          130
Ather          124
BYD            120
Kia            114
tata            10
Tata Motors     10
TATA             6
Name: count, dtype: int64

In [25]:
df["Manufacturer"] = df["Manufacturer"].str.title()

In [26]:
df["Manufacturer"].value_counts()

Manufacturer
Hyundai        154
Tata           146
Ola            139
Mahindra       132
Mg             131
Tesla          130
Ather          124
Byd            120
Kia            114
Tata Motors     10
Name: count, dtype: int64

In [27]:
df["Manufacturer"] = df["Manufacturer"].replace({'Tata Motors':'Tata','TATA':'Tata','tata':'Tata','Mg':'MG','Byd':'BYD','Ola':'OLA','Kia':'KIA'})

In [28]:
df["Manufacturer"].value_counts()

Manufacturer
Tata        156
Hyundai     154
OLA         139
Mahindra    132
MG          131
Tesla       130
Ather       124
BYD         120
KIA         114
Name: count, dtype: int64

In [29]:
df.groupby("Manufacturer")["Units_Sold"].sum()

Manufacturer
Ather       2467.0
BYD         4014.0
Hyundai     4179.0
KIA         2879.0
MG          2721.0
Mahindra    4385.0
OLA         2888.0
Tata        2904.0
Tesla       3559.0
Name: Units_Sold, dtype: float64

In [30]:
df["City"].value_counts()

City
Lucknow       120
Kochi         110
Ahmedabad     104
Kolkata       102
Bengaluru     100
Jaipur         99
Pune           96
Chennai        95
Hyderabad      94
Nagpur         89
Delhi          83
Mumbai         83
mumbai          8
pune            5
Bengaluru       5
Pune            4
Mumbai          3
Name: count, dtype: int64

In [31]:
df["City"] = df["City"].str.strip()

In [32]:
df["City"].value_counts()

City
Lucknow      120
Kochi        110
Bengaluru    105
Ahmedabad    104
Kolkata      102
Pune         100
Jaipur        99
Chennai       95
Hyderabad     94
Nagpur        89
Mumbai        86
Delhi         83
mumbai         8
pune           5
Name: count, dtype: int64

In [33]:
df.columns

Index(['Record_ID', 'Registration_Date', 'Manufacturer', 'Model',
       'Vehicle_Category', 'City', 'State', 'Price_INR', 'Battery_Range_KM',
       'Units_Sold', 'Charging_Type', 'Area_Type'],
      dtype='object')

In [34]:
df["City"] = df["City"].str.title()

In [35]:
df["City"].value_counts()

City
Lucknow      120
Kochi        110
Bengaluru    105
Pune         105
Ahmedabad    104
Kolkata      102
Jaipur        99
Chennai       95
Mumbai        94
Hyderabad     94
Nagpur        89
Delhi         83
Name: count, dtype: int64

In [36]:
df["State"].value_counts()

State
Delhi            141
West Bengal      128
Rajasthan        126
Maharashtra      125
Tamil Nadu       120
Telangana        117
Gujarat          110
Uttar Pradesh    110
Kerala           104
Karnataka        101
Name: count, dtype: int64

In [37]:
df["State"].value_counts(dropna=False)

State
Delhi            141
West Bengal      128
Rajasthan        126
Maharashtra      125
Tamil Nadu       120
Telangana        117
Uttar Pradesh    110
Gujarat          110
Kerala           104
Karnataka        101
NaN               18
Name: count, dtype: int64

In [38]:
df[df["State"].isna()][["City","State"]]

           City State
84      Lucknow   NaN
89    Hyderabad   NaN
153     Chennai   NaN
178     Chennai   NaN
202     Lucknow   NaN
217   Bengaluru   NaN
246       Kochi   NaN
267       Delhi   NaN
314   Ahmedabad   NaN
390       Kochi   NaN
395   Hyderabad   NaN
413     Chennai   NaN
617   Hyderabad   NaN
702       Kochi   NaN
912   Hyderabad   NaN
971      Mumbai   NaN
1092    Kolkata   NaN
1119  Ahmedabad   NaN

In [39]:
df.iloc[84]

Record_ID                EV100084
Registration_Date      2024-11-09
Manufacturer                  OLA
Model                      S1 Pro
Vehicle_Category     Electric Car
City                      Lucknow
State                         NaN
Price_INR                 1337942
Battery_Range_KM            335.0
Units_Sold                   12.0
Charging_Type              Public
Area_Type                   Rural
Name: 84, dtype: object

In [40]:
city_state_map = {
    'Lucknow': 'Uttar Pradesh',
    'Hyderabad': 'Telangana',
    'Chennai': 'Tamil Nadu',
    'Bengaluru': 'Karnataka',
    'Kochi': 'Kerala',
    'Delhi': 'Delhi',
    'Ahmedabad': 'Gujarat',
    'Mumbai': 'Maharashtra',
    'Kolkata': 'West Bengal',
    'Pune': 'Maharashtra',
    'Nagpur': 'Maharashtra',
    'Jaipur': 'Rajasthan'
}

In [41]:
df["State"] = df["State"].fillna(df["State"].map(city_state_map))

In [42]:
df["State"].isna().sum()

np.int64(18)

In [43]:
df.loc[df["State"].isna(),["City","State"]]

           City State
84      Lucknow   NaN
89    Hyderabad   NaN
153     Chennai   NaN
178     Chennai   NaN
202     Lucknow   NaN
217   Bengaluru   NaN
246       Kochi   NaN
267       Delhi   NaN
314   Ahmedabad   NaN
390       Kochi   NaN
395   Hyderabad   NaN
413     Chennai   NaN
617   Hyderabad   NaN
702       Kochi   NaN
912   Hyderabad   NaN
971      Mumbai   NaN
1092    Kolkata   NaN
1119  Ahmedabad   NaN

In [44]:
df["State"].map(city_state_map)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
       ...
1195    NaN
1196    NaN
1197    NaN
1198    NaN
1199    NaN
Name: State, Length: 1200, dtype: object

In [45]:
df[df["State"].isna()][["City","State"]]

           City State
84      Lucknow   NaN
89    Hyderabad   NaN
153     Chennai   NaN
178     Chennai   NaN
202     Lucknow   NaN
217   Bengaluru   NaN
246       Kochi   NaN
267       Delhi   NaN
314   Ahmedabad   NaN
390       Kochi   NaN
395   Hyderabad   NaN
413     Chennai   NaN
617   Hyderabad   NaN
702       Kochi   NaN
912   Hyderabad   NaN
971      Mumbai   NaN
1092    Kolkata   NaN
1119  Ahmedabad   NaN

In [46]:
df.loc[df["State"].isna(),"City"].value_counts()

City
Hyderabad    4
Kochi        3
Chennai      3
Lucknow      2
Ahmedabad    2
Bengaluru    1
Delhi        1
Mumbai       1
Kolkata      1
Name: count, dtype: int64

In [47]:
df["State"].isnull().sum()

np.int64(18)

In [48]:
city_state_map = {
    'Lucknow': 'Uttar Pradesh',
    'Hyderabad': 'Telangana',
    'Chennai': 'Tamil Nadu',
    'Bengaluru': 'Karnataka',
    'Kochi': 'Kerala',
    'Delhi': 'Delhi',
    'Ahmedabad': 'Gujarat',
    'Mumbai': 'Maharashtra',
    'Kolkata': 'West Bengal',
    'Pune': 'Maharashtra',
    'Nagpur': 'Maharashtra',
    'Jaipur': 'Rajasthan'
}

In [49]:
df["State"] = df["State"].fillna(df["State"].map(city_state_map))

In [50]:
df["State"].isna().sum()

np.int64(18)

In [51]:
print(df.loc[df['State'].isna(), 'City'].tolist())

['Lucknow', 'Hyderabad', 'Chennai', 'Chennai', 'Lucknow', 'Bengaluru', 'Kochi', 'Delhi', 'Ahmedabad', 'Kochi', 'Hyderabad', 'Chennai', 'Hyderabad', 'Kochi', 'Hyderabad', 'Mumbai', 'Kolkata', 'Ahmedabad']

In [52]:
mask = df['State'].isna()

df.loc[mask, 'State'] = df.loc[mask, 'City'].map(city_state_map)

In [53]:
df["State"].isna().sum()

np.int64(0)

In [54]:
df.isnull().sum()

Record_ID             0
Registration_Date     0
Manufacturer          0
Model                 0
Vehicle_Category      0
City                  0
State                 0
Price_INR            18
Battery_Range_KM     28
Units_Sold            5
Charging_Type         0
Area_Type             0
dtype: int64

In [55]:
df["Price_INR"].info()

<class 'pandas.core.series.Series'>
Index: 1200 entries, 0 to 1199
Series name: Price_INR
Non-Null Count  Dtype
--------------  -----
1182 non-null   object
dtypes: object(1)
memory usage: 18.8+ KB

In [56]:
df["Price_INR"].head(20)

0      200075
1       97011
2      250000
3     2386927
4     3456598
5      231036
6      106331
7     2335295
8      172199
9      167924
10    2364659
11     173033
12     231671
13     350000
14     223069
15     101604
16    2519636
17    1863867
18    2285962
19     207914
Name: Price_INR, dtype: object

In [57]:
df["Price_INR"].unique()[:20]

array(['200075', '97011', '250000', '2386927', '3456598', '231036',
       '106331', '2335295', '172199', '167924', '2364659', '173033',
       '231671', '350000', '223069', '101604', '2519636', '1863867',
       '2285962', '207914'], dtype=object)

In [69]:
df["Price_INR"].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Price_INR, dtype: float64

In [58]:
df[df["Price_INR"].isna()][["Model","Vehicle_Category","Price_INR"]]

          Model  Vehicle_Category Price_INR
36       XEV 9e      Electric Car       NaN
78    Carens EV      Electric Car       NaN
104   Carens EV     Electric Bike       NaN
270        450X  Electric Scooter       NaN
299      S1 Pro      Electric Car       NaN
304          e6  Electric Scooter       NaN
393   Carens EV  Electric Scooter       NaN
408       Rizta  Electric Scooter       NaN
454        Seal  Electric Scooter       NaN
469        S1 X  Electric Scooter       NaN
473     Model Y  Electric Scooter       NaN
560      S1 Pro  Electric Scooter       NaN
627        450X      Electric Car       NaN
688       ZS EV  Electric Scooter       NaN
778        450X  Electric Scooter       NaN
834       Rizta  Electric Scooter       NaN
873        BE 6      Electric Car       NaN
1075      Rizta      Electric Car       NaN

In [62]:
df["Price_INR"].isnull().sum()

np.int64(18)

In [73]:
df["Price_INR"] = pd.to_numeric(df['Price_INR'], errors='coerce')

In [74]:
df["Price_INR"].info()

<class 'pandas.core.series.Series'>
Index: 1200 entries, 0 to 1199
Series name: Price_INR
Non-Null Count  Dtype
--------------  -----
0 non-null      float64
dtypes: float64(1)
memory usage: 18.8 KB

In [75]:
df["Price_INR"].isna().sum()

np.int64(1200)

In [76]:
df["Price_INR"].isnull().sum()

np.int64(1200)

In [77]:
df["Price_INR"].head()

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
Name: Price_INR, dtype: float64